// Workout v1.3.7 – layout per spesifikasjon, PI klikkbar, prev/next fix, reset on discard, W↔W/kg

const WorkoutEngine=(function(){
  const S={ running:false, paused:false, timer:null, plan:null, seq:[], idx:0, left:0, tTot:0, tDrag:0, dist:0,
            hrBuf:[], speedUnit:'kmh', powerUnit:'W', rpeCur:6,
            hrSamples:[], spdSamples:[], powSamples:[], seriesHr:[], seriesSpd:[], seriesInc:[], perDrag:[] };
  function expand(blocks){ const out=[]; (blocks||[]).forEach(b=>{ if(['Oppvarming','Pause','Nedjogg'].includes(b.kind)) out.push({kind:b.kind,dur:b.dur}); else if(b.kind==='Intervall'){ for(let i=1;i<=b.reps;i++){ out.push({kind:'Arbeid',dur:b.work,rep:i,reps:b.reps}); if(b.rest>0) out.push({kind:'Pause',dur:b.rest}); } } else if(b.kind==='Serie'){ for(let s=1;s<=b.series;s++){ for(let i=1;i<=b.reps;i++){ out.push({kind:'Arbeid',dur:b.work,rep:i,reps:b.reps,set:s,sets:b.series}); if(b.rest>0) out.push({kind:'Pause',dur:b.rest}); } if(s<b.series && b.seriesRest) out.push({kind:'Pause',dur:b.seriesRest}); } } else if(b.kind==='Fartlek'){ for(let i=1;i<=b.reps;i++){ out.push({kind:'Arbeid',dur:b.on, rep:i, reps:b.reps}); out.push({kind:'Arbeid',dur:b.off, rep:i, reps:b.reps}); } } }); return out; }
  function fmtSpd(kmh){ if(S.speedUnit==='kmh') return `${kmh.toFixed(1)} km/t`; if(kmh<=0) return '–'; const pace=60/(kmh); const m=Math.floor(pace), s=Math.round((pace-m)*60); return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')} min/km`; }
  function estWatt(speedKmh, inclinePct){ const v=(speedKmh||0)/3.6; const i=(inclinePct||0)/100; const met=(AppState.settings?.met_eff)||0.25; const mass=(AppState.settings?.mass)||75; const shoe=1-((AppState.settings?.shoe_gain_pct||0)/100); const tm=(AppState.settings?.tm_cal||1); const Wkg_met=4.185*v + (9.81*v*i)/met; const Wkg=Wkg_met*shoe*tm; return { Wkg, W: Wkg*mass } }
  function reset(){ S.running=false; S.paused=false; if(S.timer){ clearInterval(S.timer); S.timer=null; } S.seq=[]; S.idx=0; S.left=0; S.tTot=0; S.tDrag=0; S.dist=0; S.hrBuf=[]; S.hrSamples=[]; S.spdSamples=[]; S.powSamples=[]; S.seriesHr=[]; S.seriesSpd=[]; S.seriesInc=[]; S.perDrag=[]; }

  function setPhase(){ const cur=S.seq[S.idx]; if(!cur){ finish(true); return; } S.left=cur.dur; updateUI(); }
  function start(){ if(S.running) return; S.running=true; S.paused=false; if(!S.timer) S.timer=setInterval(tick,1000); AppState.session.running=true; AppState.session.paused=false; bindButtons(); updateUI(); }
  function pause(){ S.paused=!S.paused; AppState.session.paused=S.paused; const b=document.getElementById('wk_pause'); if(b) b.textContent=S.paused?'Gjenoppta':'Pause'; }
  function prev(){ S.idx=Math.max(0,S.idx-1); setPhase(); }
  function next(){ S.idx=Math.min(S.seq.length, S.idx+1); setPhase(); }
  function finish(saved){ if(S.timer){ clearInterval(S.timer); S.timer=null; } const plan=S.plan; const session=saved? {id:'s_'+Date.now(), name:plan.name, endedAt:Date.now(), dist:S.dist, total:S.tTot, seq:S.seq, perDrag:S.perDrag, hrSeries:S.seriesHr, spdSeries:S.seriesSpd, incSeries:S.seriesInc, notes:''} : null; reset(); if(saved&&session){ const st=AppState; st.logg=st.logg||[]; st.logg.push(session); Storage.saveP(AppState.currentProfile,'logg', st.logg); location.hash = '#/result?id='+session.id; } else { // forkast: nullstill og gå tilbake til økt start
    S.plan=plan; S.seq=expand(plan.blocks); S.idx=0; S.left=S.seq[0]?S.seq[0].dur:0; updateUI();
  } }

  function tick(){ if(S.paused||!S.running) return; S.tTot++; const cur=S.seq[S.idx]; const spdNow = cur.kind==='Pause'?0:(AppState.tm?.speed||0); const incNow=AppState.tm?.incline||0; const hrNow=AppState.hr?.bpm||0; S.dist += spdNow/3600; S.seriesSpd.push({t:Date.now()/1000, kmh:spdNow}); S.seriesInc.push({t:Date.now()/1000, pct:incNow}); if(hrNow) S.seriesHr.push({t:Date.now()/1000, bpm:hrNow}); if(cur.kind==='Arbeid'){ if(hrNow) S.hrSamples.push(hrNow); S.spdSamples.push(spdNow); S.powSamples.push(estWatt(spdNow,incNow).W); S.tDrag++; } drawGraph(); updateUI(); S.left--; if(S.left<=0){ if(cur.kind==='Arbeid'){ const aHR=Math.round(S.hrSamples.reduce((a,b)=>a+b,0)/(S.hrSamples.length||1)); const aSpd=(S.spdSamples.reduce((a,b)=>a+b,0)/(S.spdSamples.length||1)); const aW=(S.powSamples.reduce((a,b)=>a+b,0)/(S.powSamples.length||1)); S.perDrag.push({hr:aHR, spd:+aSpd.toFixed(1), watt:+(aW||0).toFixed(0), rpe:S.rpeCur}); S.hrSamples.length=0; S.spdSamples.length=0; S.powSamples.length=0; } S.idx++; setPhase(); } }

  function updateUI(){ const spdNow=AppState.tm?.speed||0, incNow=AppState.tm?.incline||0, hrNow=AppState.hr?.bpm||0; const hrEl=document.getElementById('wk_hr'); if(hrEl) hrEl.textContent=String(hrNow||0); const hrp=document.getElementById('wk_hrp'); if(hrp){ const r=AppState.settings?.hrrest||50, m=AppState.settings?.hrmax||190; const p=(hrNow-r)/Math.max(1,(m-r)); hrp.textContent=isFinite(p)? `${Math.round(p*100)}% av HRmax`:'–'; } const slopeEl=document.getElementById('wk_slope'); if(slopeEl) slopeEl.textContent=`${(incNow||0).toFixed(2)}%`; const spdEl=document.getElementById('wk_spd'); if(spdEl) spdEl.textContent=fmtSpd(spdNow); const incEl=document.getElementById('wk_inc'); if(incEl) incEl.textContent=`${Math.round(incNow)}%`; const p=estWatt(spdNow,incNow); const pow=document.getElementById('wk_pow'); if(pow){ pow.textContent = (S.powerUnit==='W')? `${Math.round(p.W)} W` : `${p.Wkg.toFixed(2)} W/kg`; }
    try{ const res=(typeof PI!=='undefined')? PI.compute(performance.now(), {prevTime:null,tSec:0,hr:hrNow,speedKmh:spdNow,inclinePct:incNow,tempC:20,rpe:S.rpeCur,cumSweatL:0}):null; const pi=document.getElementById('wk_pi'); if(pi) pi.textContent=res&&res.PI? res.PI.toFixed(2):'–'; const d=document.getElementById('wk_dhr'); if(d) d.textContent=res? String(Math.round(res.dHR||0)):'0'; }catch(_e){}
    const eTimer=document.getElementById('wk_timer'); if(eTimer) eTimer.textContent=UI.fmtTime(S.left); const eTot=document.getElementById('wk_tTot'); if(eTot) eTot.textContent=UI.fmtTime(S.tTot); const eDrag=document.getElementById('wk_tDrag'); if(eDrag) eDrag.textContent=UI.fmtTime(S.tDrag); const eDist=document.getElementById('wk_dist'); if(eDist) eDist.textContent=S.dist.toFixed(2); }

  let c,ctx; function initGraph(host){ c=document.createElement('canvas'); c.width=900; c.height=260; c.style.width='100%'; ctx=c.getContext('2d'); host.appendChild(c); const ro=new ResizeObserver(()=>{ const r=host.getBoundingClientRect(); c.width=Math.max(600,Math.floor(r.width)); c.height=260; drawGraph(); }); ro.observe(host); }
  function drawGraph(){ if(!ctx) return; const W=c.width,H=c.height; ctx.clearRect(0,0,W,H); ctx.strokeStyle='#b4c4e8'; ctx.strokeRect(40,10,W-60,H-30); const t1=Date.now()/1000, t0=t1-15*60; ctx.strokeStyle='#d93c3c'; ctx.lineWidth=2; ctx.beginPath(); let first=true; for(const p of S.seriesHr){ if(p.t<t0) continue; const x=40+((p.t-t0)/(15*60))*(W-60); const y=10+(1-((p.bpm-90)/(190-90)))*(H-30); if(first){ ctx.moveTo(x,y); first=false;} else ctx.lineTo(x,y);} ctx.stroke(); ctx.strokeStyle='#d6a600'; ctx.lineWidth=2; ctx.beginPath(); first=true; for(const p of S.seriesSpd){ if(p.t<t0) continue; const x=40+((p.t-t0)/(15*60))*(W-60); const y=10+(1-((p.kmh-0)/20))*(H-30); if(first){ ctx.moveTo(x,y); first=false;} else ctx.lineTo(x,y);} ctx.stroke(); ctx.fillStyle='#0b1220'; ctx.font='12px system-ui'; [90,110,130,150,170,190].forEach(v=>{ const y=10+(1-((v-90)/100))*(H-30); ctx.fillText(String(v),8,y+4); }); [0,5,10,15,20].forEach(v=>{ const y=10+(1-(v/20))*(H-30); ctx.fillText(String(v), W-28, y+4); }); }

  function bindButtons(){ const q=id=>document.getElementById(id); q('wk_start')?.addEventListener('click', start); q('wk_pause')?.addEventListener('click', pause); q('wk_prev')?.addEventListener('click', prev); q('wk_next')?.addEventListener('click', next); q('wk_save')?.addEventListener('click', ()=>finish(true)); q('wk_discard')?.addEventListener('click', ()=>{ if(confirm('Forkaste? Økta nullstilles.')) finish(false); }); q('wk_spdDec')?.addEventListener('click', ()=>{ AppState.tm.speed=Math.max(0,(AppState.tm.speed||0)-0.1); AppState.tm.manualUntil=Date.now()+4000; updateUI(); }); q('wk_spdInc')?.addEventListener('click', ()=>{ AppState.tm.speed=(AppState.tm.speed||0)+0.1; AppState.tm.manualUntil=Date.now()+4000; updateUI(); }); q('wk_incDec')?.addEventListener('click', ()=>{ AppState.tm.incline=Math.max(0,(AppState.tm.incline||0)-1); AppState.tm.manualUntil=Date.now()+4000; updateUI(); }); q('wk_incInc')?.addEventListener('click', ()=>{ AppState.tm.incline=(AppState.tm.incline||0)+1; AppState.tm.manualUntil=Date.now()+4000; updateUI(); }); q('wk_q10')?.addEventListener('click', ()=>{ AppState.tm.speed=10; AppState.tm.manualUntil=Date.now()+4000; updateUI(); }); q('wk_q15')?.addEventListener('click', ()=>{ AppState.tm.speed=15; AppState.tm.manualUntil=Date.now()+4000; updateUI(); }); q('wk_pow')?.addEventListener('click', ()=>{ WorkoutEngine.S.powerUnit=(WorkoutEngine.S.powerUnit==='W'?'Wkg':'W'); updateUI(); }); q('wk_spd')?.addEventListener('click', ()=>{ WorkoutEngine.S.speedUnit=(WorkoutEngine.S.speedUnit==='kmh'?'pace':'kmh'); updateUI(); }); q('wk_pi')?.addEventListener('click', ()=>{ location.hash='#/pi?from=workout'; }); q('wk_rpeDec')?.addEventListener('click', ()=>{ S.rpeCur=Math.max(1,(S.rpeCur||6)-0.5); document.getElementById('wk_rpe').textContent=S.rpeCur.toFixed(1); }); q('wk_rpeInc')?.addEventListener('click', ()=>{ S.rpeCur=Math.min(10,(S.rpeCur||6)+0.5); document.getElementById('wk_rpe').textContent=S.rpeCur.toFixed(1); }); }

  function init(plan){ if(S.plan) return; S.plan=plan; S.seq=expand(plan.blocks); S.idx=0; S.left=S.seq[0]?S.seq[0].dur:0; S.tTot=0; S.tDrag=0; S.dist=0; }
  function attach(){ bindButtons(); updateUI(); }

  return { S, init, attach, initGraph };
})();

const Workout={ onHR:null,onTM:null, render(el,st){ el.innerHTML=''; const plan=st.plan || (st.workouts&&st.workouts[0]); if(!plan){ el.textContent='Ingen økt valgt.'; return; }
  // Panel slik som skissen (venstre HR/slope, midt fart/stigning m/knapper, høyre watt/PI/dHR)
  const panel=UI.h('div',{class:'card'}); panel.style.display='grid'; panel.style.gridTemplateColumns='1.1fr 1.2fr 1fr'; panel.style.gap='.5rem';
  const left=UI.h('div',{}); left.append(UI.h('div',{class:'small'},'Puls')); left.append(UI.h('div',{id:'wk_hr',style:'font-size:3.2rem;font-weight:700'},'0')); left.append(UI.h('div',{id:'wk_hrp',class:'small'},'0% av HRmax')); left.append(UI.h('div',{class:'small',style:'margin-top:.4rem'},'Slope')); left.append(UI.h('div',{id:'wk_slope',style:'font-size:1.6rem'},'0.00%'));
  const mid=UI.h('div',{}); mid.append(UI.h('div',{class:'small'},'Fart')); mid.append(UI.h('div',{id:'wk_spd',style:'font-size:1.8rem;cursor:pointer'},'0.0 km/t')); const rowBtns=UI.h('div',{class:'controls'}); rowBtns.append(UI.h('button',{class:'btn',id:'wk_q10'},'10 km/t'), UI.h('button',{class:'btn',id:'wk_q15'},'15 km/t')); const spdCtl=UI.h('div',{class:'controls'}); spdCtl.append(UI.h('button',{class:'btn',id:'wk_spdDec'},'−'), UI.h('button',{class:'btn',id:'wk_spdInc'},'+')); mid.append(rowBtns, spdCtl); mid.append(UI.h('div',{class:'small',style:'margin-top:.4rem'},'Stigning')); mid.append(UI.h('div',{id:'wk_inc',style:'font-size:1.6rem'},'0%')); const incCtl=UI.h('div',{class:'controls'}); incCtl.append(UI.h('button',{class:'btn',id:'wk_incDec'},'−'), UI.h('button',{class:'btn',id:'wk_incInc'},'+')); mid.append(incCtl);
  const right=UI.h('div',{}); right.append(UI.h('div',{class:'small'},'Watt (est.)')); right.append(UI.h('div',{id:'wk_pow',style:'font-size:1.6rem;cursor:pointer'},'0 W')); right.append(UI.h('div',{class:'small'},'PI (trykk for detalj)')); right.append(UI.h('div',{id:'wk_pi',style:'font-size:1.6rem;cursor:pointer'},'–')); right.append(UI.h('div',{class:'small'},'HR-drift  (bpm)')); right.append(UI.h('div',{id:'wk_dhr',style:'font-size:1.6rem'},'0'));
  panel.append(left, mid, right);

  // Graph + right column controls
  const graf=UI.h('div',{class:'card'}); const rightCol=UI.h('div',{}); const ctrl=UI.h('div',{class:'card'});
  ctrl.append(UI.h('div',{}, plan.name), UI.h('div',{id:'wk_phase',class:'list-item'},'–'), UI.h('div',{id:'wk_next',class:'small'},'')); const timer=UI.h('div',{id:'wk_timer',style:'font-size:2rem'},'00:00'); ctrl.append(timer);
  const btns=UI.h('div',{class:'controls'}); btns.append(UI.h('button',{class:'btn primary',id:'wk_start'},'Start'), UI.h('button',{class:'btn',id:'wk_pause'},'Pause'), UI.h('button',{class:'btn',id:'wk_prev'},'⟵'), UI.h('button',{class:'btn',id:'wk_next'},'⟶'), UI.h('button',{class:'btn',id:'wk_save'},'Lagre'), UI.h('button',{class:'btn danger',id:'wk_discard'},'Forkast')); ctrl.append(btns);
  const stats=UI.h('div',{class:'card'}); const tbl=document.createElement('table'); tbl.className='table'; tbl.innerHTML='<tr><th>Param.</th><th>Verdi</th></tr>'+
    '<tr><td>Totaltid</td><td id="wk_tTot">00:00</td></tr>'+
    '<tr><td>Dragtid</td><td id="wk_tDrag">00:00</td></tr>'+
    '<tr><td>Distanse (km)</td><td id="wk_dist">0.00</td></tr>'+
    '<tr><td>Snittpuls (drag)</td><td id="wk_avgHR">-</td></tr>'+
    '<tr><td>Snittfart (drag)</td><td id="wk_avgSpd">-</td></tr>'+
    '<tr><td>SnittWatt (drag)</td><td id="wk_avgPow">-</td></tr>'+
    '<tr><td>RPE nå</td><td><div id="wk_rpe">6.0</div><div class="controls"><button class="btn" id="wk_rpeDec">−</button><button class="btn" id="wk_rpeInc">+</button></div></td></tr>';
  stats.append(tbl);

  const grid=document.createElement('div'); grid.style.display='grid'; grid.style.gridTemplateColumns='1.6fr 1fr'; grid.style.gap='.5rem';
  const leftCol=document.createElement('div'); leftCol.append(panel, graf); const rightPanel=document.createElement('div'); rightPanel.append(ctrl, stats); grid.append(leftCol, rightPanel); el.append(grid);

  WorkoutEngine.init(plan); WorkoutEngine.initGraph(graf); WorkoutEngine.attach();
  Workout.onHR = bpm=>{ const t=Date.now()/1000; WorkoutEngine.S.hrBuf.push({t,bpm}); while(WorkoutEngine.S.hrBuf.length && (t-WorkoutEngine.S.hrBuf[0].t)>70) WorkoutEngine.S.hrBuf.shift(); WorkoutEngine.S.seriesHr.push({t,bpm}); };
  Workout.onTM = (spd,inc)=>{ const now=Date.now(); if(spd!==null && (!AppState.tm.manualUntil || now>AppState.tm.manualUntil)) AppState.tm.speed=spd; if(inc!==null) AppState.tm.incline=inc; };
} };
